# Importing Libraries and Loading the data

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 50)

In [2]:
sales_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/sales_fact.csv")
products_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/products_master.csv")
suppliers_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/suppliers_master.csv")
inventory_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/raw/inventory_snapshot.csv")
final_df = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/processed/final_df_clean.csv")

# Data Description

In [5]:
final_df = final_df.drop(columns= [col for col in final_df.columns if col.endswith('.1')])

In [7]:
final_df.columns

Index(['date', 'sku_id', 'units_sold', 'selling_price', 'gross_revenue',
       'promo_flag', 'discount_pct', 'month', 'week_ofear', 'day_of_week',
       'is_weekend', 'is_festival_month', 'is_payday_period', 'season_tag',
       'holiday_flag', 'weather_index', 'campaign_intensity',
       'platform_traffic_source', 'traffic_index', 'competitor_price_index',
       'competitor_stockout_flag', 'bundle_offer_flag',
       'stock_visibility_score', 'rating_score', 'review_volume',
       'product_visibility_rank', 'sku_name', 'category', 'sub_category',
       'mrp', 'cost_price', 'supplier_id', 'supplier_name', 'avg_lead_time',
       'lead_time_variability', 'current_stock', 'safety_stock',
       'reorder_point', 'lead_time_days', 'inbound_shipment_qty'],
      dtype='object')

In [8]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      14640 non-null  object
 1   sku_id                    14640 non-null  object
 2   units_sold                14640 non-null  int64
 3   selling_price             14640 non-null  float64
 4   gross_revenue             14640 non-null  float64
 5   promo_flag                14640 non-null  int64
 6   discount_pct              14640 non-null  float64
 7   month                     14640 non-null  int64
 8   week_ofear                14640 non-null  int64
 9   day_of_week               14640 non-null  int64
 10  is_weekend                14640 non-null  int64
 11  is_festival_month         14640 non-null  int64
 12  is_payday_period          14640 non-null  int64
 13  season_tag                14640 non-null  object
 14  holiday_flag              14640 non-null  int64
 15  weather_index             14640 non-null  float64
 16  campaign_intensity        14640 non-null  int64
 17  platform_traffic_source   14640 non-null  object
 18  traffic_index             14640 non-null  float64
 19  competitor_price_index    14640 non-null  float64
 20  competitor_stockout_flag  14640 non-null  int64
 21  bundle_offer_flag         14640 non-null  int64
 22  stock_visibility_score    14640 non-null  float64
 23  rating_score              14640 non-null  float64
 24  review_volume             14640 non-null  int64
 25  product_visibility_rank   14640 non-null  int64
 26  sku_name                  14640 non-null  object
 27  category                  14640 non-null  object
 28  sub_category              14640 non-null  object
 29  mrp                       14640 non-null  int64
 30  cost_price                14640 non-null  float64
 31  supplier_id               14640 non-null  object
 32  supplier_name             14640 non-null  object
 33  avg_lead_time             14640 non-null  int64
 34  lead_time_variability     14640 non-null  int64
 35  current_stock             14640 non-null  int64
 36  safety_stock              14640 non-null  int64
 37  reorder_point             14640 non-null  int64
 38  lead_time_days            14640 non-null  int64
 39  inbound_shipment_qty      14640 non-null  int64
dtypes: float64(9), int64(22), object(9)
memory usage: 4.5+ MB

In [9]:
final_df.describe()

,units_sold,selling_price,gross_revenue,promo_flag,discount_pct,month,week_ofear,day_of_week,is_weekend,is_festival_month,is_payday_period,holiday_flag,weather_index,campaign_intensity,traffic_index,competitor_price_index,competitor_stockout_flag,bundle_offer_flag,stock_visibility_score,rating_score,review_volume,product_visibility_rank,mrp,cost_price,avg_lead_time,lead_time_variability,current_stock,safety_stock,reorder_point,lead_time_days,inbound_shipment_qty
count,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000,14640.000000
mean,29.527937,857.719078,24805.086579,0.250683,0.113006,6.513661,26.360656,2.986339,0.284153,0.251366,0.442623,0.073770,0.991214,0.480874,1.051385,1.000321,0.114754,0.185792,0.627518,4.128250,262.325000,60.063046,967.075000,591.606500,7.425000,3.000000,611.375000,228.600000,474.900000,7.425000,120.200000
std,7.670758,493.540062,14402.340537,0.433421,0.125486,3.451352,15.085375,2.003434,0.451025,0.433813,0.496714,0.261406,0.155927,0.696161,0.077695,0.021047,0.318736,0.388952,0.189643,0.614545,149.066553,34.181026,533.108603,332.591761,3.419821,1.000034,307.093839,111.462499,218.442439,3.419821,91.852797
min,10.000000,111.520000,2653.400000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505258,0.000000,0.913340,0.949245,0.000000,0.000000,0.174916,3.010000,22.000000,1.000000,223.000000,128.470000,3.000000,2.000000,164.000000,56.000000,148.000000,3.000000,2.000000
25%,24.000000,488.870000,13311.705000,0.000000,0.033800,4.000000,13.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.887381,0.000000,0.992392,0.986368,0.000000,0.000000,0.460830,3.595000,152.000000,31.000000,570.250000,327.690000,5.000000,2.000000,368.750000,127.250000,296.750000,5.000000,47.500000
50%,28.000000,756.320000,22808.855000,0.000000,0.067000,7.000000,26.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.002854,0.000000,1.026196,1.001778,0.000000,0.000000,0.655225,4.230000,232.500000,60.000000,891.000000,526.365000,6.000000,3.000000,535.000000,206.000000,415.500000,6.000000,102.500000
75%,34.000000,1123.630000,32783.270000,1.000000,0.101225,10.000000,39.000000,5.000000,1.000000,1.000000,1.000000,0.000000,1.104804,1.000000,1.100740,1.013988,0.000000,0.000000,0.781039,4.702500,418.250000,90.000000,1306.000000,795.767500,10.000000,4.000000,807.500000,312.250000,685.500000,10.000000,175.250000
max,60.000000,2374.290000,92942.400000,1.000000,0.499900,12.000000,52.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.394342,2.000000,1.241456,1.060715,1.000000,1.000000,1.083760,4.990000,498.000000,119.000000,2375.000000,1596.060000,13.000000,4.000000,1166.000000,478.000000,874.000000,13.000000,337.000000

# Checking Null Values

In [10]:
final_df.isnull().sum() # D

date                        0
sku_id                      0
units_sold                  0
selling_price               0
gross_revenue               0
promo_flag                  0
discount_pct                0
month                       0
week_ofear                  0
day_of_week                 0
is_weekend                  0
is_festival_month           0
is_payday_period            0
season_tag                  0
holiday_flag                0
weather_index               0
campaign_intensity          0
platform_traffic_source     0
traffic_index               0
competitor_price_index      0
competitor_stockout_flag    0
bundle_offer_flag           0
stock_visibility_score      0
rating_score                0
review_volume               0
product_visibility_rank     0
sku_name                    0
category                    0
sub_category                0
mrp                         0
cost_price                  0
supplier_id                 0
supplier_name               0
avg_lead_time               0
lead_time_variability       0
current_stock               0
safety_stock                0
reorder_point               0
lead_time_days              0
inbound_shipment_qty        0
dtype: int64

In [ ]:
sales_df.isnull().sum()

date                        0
sku_id                      0
units_sold                  0
selling_price               0
gross_revenue               0
promo_flag                  0
discount_pct                0
month                       0
week_of_year                0
day_of_week                 0
is_weekend                  0
is_festival_month           0
is_payday_period            0
season_tag                  0
holiday_flag                0
weather_index               0
campaign_intensity          0
platform_traffic_source     0
traffic_index               0
competitor_price_index      0
competitor_stockout_flag    0
bundle_offer_flag           0
stock_visibility_score      0
rating_score                0
review_volume               0
product_visibility_rank     0
dtype: int64

In [42]:
products_df.isnull().sum()

sku_id          0
sku_name        0
category        0
sub_category    0
mrp             0
cost_price      0
supplier_id     0
dtype: int64

In [43]:
inventory_df.isnull().sum()

sku_id                  0
current_stock           0
safety_stock            0
reorder_point           0
lead_time_days          0
inbound_shipment_qty    0
supplier_id             0
dtype: int64

In [44]:
suppliers_df.isnull().sum()

supplier_id              0
supplier_name            0
avg_lead_time            0
lead_time_variability    0
dtype: int64

# Checking Duplicates

In [45]:
sales_df.duplicated().sum()

np.int64(0)

In [46]:
products_df.duplicated().sum()

np.int64(0)

In [47]:
inventory_df.duplicated().sum()

np.int64(0)

In [48]:
suppliers_df.duplicated().sum()

np.int64(0)

In [49]:
# Primary Key Validation

products_df['sku_id'].duplicated().sum()

np.int64(0)

In [50]:
suppliers_df["supplier_id"].duplicated().sum()

np.int64(0)

In [51]:
sales_df[
    ~sales_df["sku_id"].isin(
        products_df["sku_id"]
    )
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [52]:
products_df[
    ~products_df["supplier_id"].isin(
        suppliers_df["supplier_id"]
    )
]

Empty DataFrame
Columns: [sku_id, sku_name, category, sub_category, mrp, cost_price, supplier_id]
Index: []

In [53]:
sales_df[
    sales_df['units_sold'] <0
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [54]:
# Negative Stock Validation

inventory_df[
    inventory_df['current_stock']<0
]

Empty DataFrame
Columns: [sku_id, current_stock, safety_stock, reorder_point, lead_time_days, inbound_shipment_qty, supplier_id]
Index: []

In [55]:
sales_df[
    sales_df['discount_pct']>100
]

Empty DataFrame
Columns: [date, sku_id, units_sold, selling_price, gross_revenue, promo_flag, discount_pct, month, week_of_year, day_of_week, is_weekend, is_festival_month, is_payday_period, season_tag, holiday_flag, weather_index, campaign_intensity, platform_traffic_source, traffic_index, competitor_price_index, competitor_stockout_flag, bundle_offer_flag, stock_visibility_score, rating_score, review_volume, product_visibility_rank]
Index: []

In [56]:
products_df[
    products_df['cost_price'] > products_df['mrp']
]

Empty DataFrame
Columns: [sku_id, sku_name, category, sub_category, mrp, cost_price, supplier_id]
Index: []

In [57]:
sales_df["date"] = pd.to_datetime(
    sales_df["date"]
)

/var/folders/qm/8t8rxfy10f7b3mdcgk6yhkgh0000gp/T/ipykernel_5058/3586225470.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_df["date"] = pd.to_datetime(

In [58]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      14640 non-null  datetime64[ns]
 1   sku_id                    14640 non-null  object
 2   units_sold                14640 non-null  int64
 3   selling_price             14640 non-null  float64
 4   gross_revenue             14640 non-null  float64
 5   promo_flag                14640 non-null  int64
 6   discount_pct              14640 non-null  float64
 7   month                     14640 non-null  int64
 8   week_of_year              14640 non-null  int64
 9   day_of_week               14640 non-null  int64
 10  is_weekend                14640 non-null  int64
 11  is_festival_month         14640 non-null  int64
 12  is_payday_period          14640 non-null  int64
 13  season_tag                14640 non-null  object
 14  holiday_flag              14640 non-null  int64
 15  weather_index             14640 non-null  float64
 16  campaign_intensity        14640 non-null  int64
 17  platform_traffic_source   14640 non-null  object
 18  traffic_index             14640 non-null  float64
 19  competitor_price_index    14640 non-null  float64
 20  competitor_stockout_flag  14640 non-null  int64
 21  bundle_offer_flag         14640 non-null  int64
 22  stock_visibility_score    14640 non-null  float64
 23  rating_score              14640 non-null  float64
 24  review_volume             14640 non-null  int64
 25  product_visibility_rank   14640 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(14), object(3)
memory usage: 2.9+ MB

In [ ]:
final_df.groupby('sub_category')['units_sold'].sum().sort_index()

sub_category
Accessories        9524
Audio             59524
Body Care         22265
Charging          36901
Cookware          20927
Floor Care        48004
Hair Care         21085
Hydration         27170
Multi-Surface      9400
Organizers        10718
PC Accessories    37613
Serveware          9902
Skin Care         21303
Storage           59102
Strength          28932
Yoga               9919
Name: units_sold, dtype: int64

In [ ]:
sku_performance = final_df.groupby('sku_id').agg(
    total_units = ('units_sold' , 'sum'),
    average_daily_units = ('units_sold' , 'mean'),
    days_with_sales=('units_sold' , 'count')
).reset_index()

In [ ]:
top_selling = sku_performance.sort_values(by="total_units", ascending=False).head(10)
print("--- TOP 10 SELLING PRODUCTS ---")
print(top_selling)

--- TOP 10 SELLING PRODUCTS ---
     sku_id  total_units  average_daily_units  days_with_sales
33  SKU0034        13755            37.581967              366
17  SKU0018        13702            37.437158              366
12  SKU0013        13656            37.311475              366
37  SKU0038        13001            35.521858              366
4   SKU0005        12718            34.748634              366
23  SKU0024        12515            34.193989              366
38  SKU0039        12417            33.926230              366
31  SKU0032        12248            33.464481              366
6   SKU0007        12175            33.265027              366
1   SKU0002        11643            31.811475              366