In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns' , None)

In [48]:
sales = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/processed/sales_clean.csv")

products = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/processed/inventory_clean.csv")

inventory = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/processed/inventory_clean.csv")

suppliers = pd.read_csv("/Users/kushal09/Documents/Documents - Krrish's MacBook Air/Career247 /Capstone_project/inventory_optimization/data/processed/suppliers_clean.csv")

In [49]:
print(sales.shape)
print(products.shape)
print(inventory.shape)
print(suppliers.shape)

(14640, 32)
(40, 7)
(40, 7)
(10, 4)

In [50]:
print(sales.columns)

print(products.columns)

print(inventory.columns)

print(suppliers.columns)

Index(['date', 'sku_id', 'units_sold', 'selling_price', 'gross_revenue',
       'promo_flag', 'discount_pct', 'month', 'week_of_year', 'day_of_week',
       'is_weekend', 'is_festival_month', 'is_payday_period', 'season_tag',
       'holiday_flag', 'weather_index', 'campaign_intensity',
       'platform_traffic_source', 'traffic_index', 'competitor_price_index',
       'competitor_stockout_flag', 'bundle_offer_flag',
       'stock_visibility_score', 'rating_score', 'review_volume',
       'product_visibility_rank', 'lag_1_units', 'lag_7_units', 'lag_30_units',
       'rolling_mean_7', 'rolling_meN_14', 'rolling_std_7'],
      dtype='object')
Index(['sku_id', 'current_stock', 'safety_stock', 'reorder_point',
       'lead_time_days', 'inbound_shipment_qty', 'supplier_id'],
      dtype='object')
Index(['sku_id', 'current_stock', 'safety_stock', 'reorder_point',
       'lead_time_days', 'inbound_shipment_qty', 'supplier_id'],
      dtype='object')
Index(['supplier_id', 'supplier_name', 'avg_lead_time',
       'lead_time_variability'],
      dtype='object')

In [123]:
sa_pro = sales.merge(
    products,
    on="sku_id",
    how="left",
    validate="many_to_one"
)

sa_pro_sup = sa_pro.merge(
    suppliers,
    on="supplier_id",
    how="left",
    validate="many_to_one"
)

master_df = sa_pro_sup.merge(
    inventory,
    on="sku_id",
    how="left",
    validate="many_to_one"
)

In [124]:
master_df.isnull().sum()

date                           0
sku_id                         0
units_sold                     0
selling_price                  0
gross_revenue                  0
promo_flag                     0
discount_pct                   0
month                          0
week_of_year                   0
day_of_week                    0
is_weekend                     0
is_festival_month              0
is_payday_period               0
season_tag                     0
holiday_flag                   0
weather_index                  0
campaign_intensity             0
platform_traffic_source        0
traffic_index                  0
competitor_price_index         0
competitor_stockout_flag       0
bundle_offer_flag              0
stock_visibility_score         0
rating_score                   0
review_volume                  0
product_visibility_rank        0
lag_1_units                   40
lag_7_units                  280
lag_30_units                1200
rolling_mean_7               280
rolling_meN_14               280
rolling_std_7                280
current_stock_x                0
safety_stock_x                 0
reorder_point_x                0
lead_time_days_x               0
inbound_shipment_qty_x         0
supplier_id_x                  0
supplier_name                  0
avg_lead_time                  0
lead_time_variability          0
current_stock_y                0
safety_stock_y                 0
reorder_point_y                0
lead_time_days_y               0
inbound_shipment_qty_y         0
supplier_id_y                  0
dtype: int64

In [125]:
master_df.drop_duplicates()

,date,sku_id,units_sold,selling_price,gross_revenue,promo_flag,discount_pct,month,week_of_year,day_of_week,is_weekend,is_festival_month,is_payday_period,season_tag,holiday_flag,weather_index,campaign_intensity,platform_traffic_source,traffic_index,competitor_price_index,competitor_stockout_flag,bundle_offer_flag,stock_visibility_score,rating_score,review_volume,product_visibility_rank,lag_1_units,lag_7_units,lag_30_units,rolling_mean_7,rolling_meN_14,rolling_std_7,current_stock_x,safety_stock_x,reorder_point_x,lead_time_days_x,inbound_shipment_qty_x,supplier_id_x,supplier_name,avg_lead_time,lead_time_variability,current_stock_y,safety_stock_y,reorder_point_y,lead_time_days_y,inbound_shipment_qty_y,supplier_id_y
0,2024-01-01,SKU0001,28,1028.54,28799.12,0,0.0072,1,1,0,0,0,1,winter,0,1.033050,1,affiliate,1.028220,1.039897,0,0,0.332970,4.99,220,14,NaN,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
1,2024-01-02,SKU0001,27,942.76,25454.52,0,0.0900,1,1,1,0,0,1,winter,0,1.075864,0,organic,1.000124,1.034213,0,0,0.332574,4.99,220,26,28.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
2,2024-01-03,SKU0001,27,1023.78,27642.06,0,0.0118,1,1,2,0,0,1,winter,0,0.776739,0,paid,1.042157,1.019800,0,0,0.369938,4.99,220,50,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
3,2024-01-04,SKU0001,29,940.90,27286.10,0,0.0918,1,1,3,0,0,1,winter,0,1.029230,0,paid,0.998036,1.004657,0,0,0.445269,4.99,220,42,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
4,2024-01-05,SKU0001,37,812.43,30059.91,1,0.2158,1,1,4,0,0,1,winter,0,1.093677,1,organic,1.047220,0.956571,0,0,0.414885,4.99,220,20,29.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,2024-12-27,SKU0040,33,1719.75,56751.75,0,0.0699,12,52,4,0,1,1,festive,0,0.766799,0,paid,1.135735,0.999664,0,1,0.481276,3.13,177,2,38.0,31.0,32.0,33.571429,33.571429,3.408672,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14636,2024-12-28,SKU0040,38,1670.94,63495.72,0,0.0963,12,52,5,1,1,1,festive,0,0.528332,1,organic,1.239253,0.980320,0,0,0.496113,3.13,177,50,33.0,32.0,50.0,33.857143,33.857143,3.236694,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14637,2024-12-29,SKU0040,40,1411.90,56476.00,1,0.2364,12,52,6,1,1,1,festive,0,0.899582,2,affiliate,1.238106,1.006364,0,0,0.534816,3.13,177,78,38.0,35.0,33.0,34.714286,34.714286,3.450328,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14638,2024-12-30,SKU0040,27,1721.79,46488.33,0,0.0688,12,1,0,0,1,1,festive,0,0.802982,0,paid,1.168117,0.977266,0,0,0.459660,3.13,177,98,40.0,31.0,37.0,35.428571,35.428571,3.994043,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14639,2024-12-31,SKU0040,37,1418.00,52466.00,1,0.2331,12,1,1,0,1,1,festive,0,1.027837,0,organic,1.165809,1.000552,0,0,0.572224,3.13,177,26,27.0,38.0,44.0,34.857143,34.857143,4.913538,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008

In [126]:
master_df.head()

,date,sku_id,units_sold,selling_price,gross_revenue,promo_flag,discount_pct,month,week_of_year,day_of_week,is_weekend,is_festival_month,is_payday_period,season_tag,holiday_flag,weather_index,campaign_intensity,platform_traffic_source,traffic_index,competitor_price_index,competitor_stockout_flag,bundle_offer_flag,stock_visibility_score,rating_score,review_volume,product_visibility_rank,lag_1_units,lag_7_units,lag_30_units,rolling_mean_7,rolling_meN_14,rolling_std_7,current_stock_x,safety_stock_x,reorder_point_x,lead_time_days_x,inbound_shipment_qty_x,supplier_id_x,supplier_name,avg_lead_time,lead_time_variability,current_stock_y,safety_stock_y,reorder_point_y,lead_time_days_y,inbound_shipment_qty_y,supplier_id_y
0,2024-01-01,SKU0001,28,1028.54,28799.12,0,0.0072,1,1,0,0,0,1,winter,0,1.033050,1,affiliate,1.028220,1.039897,0,0,0.332970,4.99,220,14,NaN,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
1,2024-01-02,SKU0001,27,942.76,25454.52,0,0.0900,1,1,1,0,0,1,winter,0,1.075864,0,organic,1.000124,1.034213,0,0,0.332574,4.99,220,26,28.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
2,2024-01-03,SKU0001,27,1023.78,27642.06,0,0.0118,1,1,2,0,0,1,winter,0,0.776739,0,paid,1.042157,1.019800,0,0,0.369938,4.99,220,50,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
3,2024-01-04,SKU0001,29,940.90,27286.10,0,0.0918,1,1,3,0,0,1,winter,0,1.029230,0,paid,0.998036,1.004657,0,0,0.445269,4.99,220,42,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
4,2024-01-05,SKU0001,37,812.43,30059.91,1,0.2158,1,1,4,0,0,1,winter,0,1.093677,1,organic,1.047220,0.956571,0,0,0.414885,4.99,220,20,29.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003

In [127]:
master_df["date"] = pd.to_datetime(master_df["date"])

In [128]:
master_df.columns.str.replace('_x' , '')

Index(['date', 'sku_id', 'units_sold', 'selling_price', 'gross_revenue',
       'promo_flag', 'discount_pct', 'month', 'week_of_year', 'day_of_week',
       'is_weekend', 'is_festival_month', 'is_payday_period', 'season_tag',
       'holiday_flag', 'weather_index', 'campaign_intensity',
       'platform_traffic_source', 'traffic_index', 'competitor_price_index',
       'competitor_stockout_flag', 'bundle_offer_flag',
       'stock_visibility_score', 'rating_score', 'review_volume',
       'product_visibility_rank', 'lag_1_units', 'lag_7_units', 'lag_30_units',
       'rolling_mean_7', 'rolling_meN_14', 'rolling_std_7', 'current_stock',
       'safety_stock', 'reorder_point', 'lead_time_days',
       'inbound_shipment_qty', 'supplier_id', 'supplier_name', 'avg_lead_time',
       'lead_time_variability', 'current_stock_y', 'safety_stock_y',
       'reorder_point_y', 'lead_time_days_y', 'inbound_shipment_qty_y',
       'supplier_id_y'],
      dtype='object')

In [129]:
reamne_map = {col: col.replace('_x' ,'') for col in master_df.columns if '_x' in col}
reamne_map2 = {col: col.replace('_y' ,'') for col in master_df.columns if '_y' in col}

In [130]:
reamne_map2 = {col: col.replace('_y' ,'') for col in master_df.columns if '_y' in col}

In [131]:
master_df = master_df.rename(columns=reamne_map)

In [132]:
master_df = master_df.rename(columns=reamne_map2)

In [133]:
master_df

,date,sku_id,units_sold,selling_price,gross_revenue,promo_flag,discount_pct,month,week_ofear,day_of_week,is_weekend,is_festival_month,is_payday_period,season_tag,holiday_flag,weather_index,campaign_intensity,platform_traffic_source,traffic_index,competitor_price_index,competitor_stockout_flag,bundle_offer_flag,stock_visibility_score,rating_score,review_volume,product_visibility_rank,lag_1_units,lag_7_units,lag_30_units,rolling_mean_7,rolling_meN_14,rolling_std_7,current_stock,safety_stock,reorder_point,lead_time_days,inbound_shipment_qty,supplier_id,supplier_name,avg_lead_time,lead_time_variability,current_stock,safety_stock,reorder_point,lead_time_days,inbound_shipment_qty,supplier_id
0,2024-01-01,SKU0001,28,1028.54,28799.12,0,0.0072,1,1,0,0,0,1,winter,0,1.033050,1,affiliate,1.028220,1.039897,0,0,0.332970,4.99,220,14,NaN,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
1,2024-01-02,SKU0001,27,942.76,25454.52,0,0.0900,1,1,1,0,0,1,winter,0,1.075864,0,organic,1.000124,1.034213,0,0,0.332574,4.99,220,26,28.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
2,2024-01-03,SKU0001,27,1023.78,27642.06,0,0.0118,1,1,2,0,0,1,winter,0,0.776739,0,paid,1.042157,1.019800,0,0,0.369938,4.99,220,50,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
3,2024-01-04,SKU0001,29,940.90,27286.10,0,0.0918,1,1,3,0,0,1,winter,0,1.029230,0,paid,0.998036,1.004657,0,0,0.445269,4.99,220,42,27.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
4,2024-01-05,SKU0001,37,812.43,30059.91,1,0.2158,1,1,4,0,0,1,winter,0,1.093677,1,organic,1.047220,0.956571,0,0,0.414885,4.99,220,20,29.0,NaN,NaN,NaN,NaN,NaN,963,282,631,10,127,SUP003,Skyline Imports Pvt. Ltd.,10,2,963,282,631,10,127,SUP003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,2024-12-27,SKU0040,33,1719.75,56751.75,0,0.0699,12,52,4,0,1,1,festive,0,0.766799,0,paid,1.135735,0.999664,0,1,0.481276,3.13,177,2,38.0,31.0,32.0,33.571429,33.571429,3.408672,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14636,2024-12-28,SKU0040,38,1670.94,63495.72,0,0.0963,12,52,5,1,1,1,festive,0,0.528332,1,organic,1.239253,0.980320,0,0,0.496113,3.13,177,50,33.0,32.0,50.0,33.857143,33.857143,3.236694,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14637,2024-12-29,SKU0040,40,1411.90,56476.00,1,0.2364,12,52,6,1,1,1,festive,0,0.899582,2,affiliate,1.238106,1.006364,0,0,0.534816,3.13,177,78,38.0,35.0,33.0,34.714286,34.714286,3.450328,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14638,2024-12-30,SKU0040,27,1721.79,46488.33,0,0.0688,12,1,0,0,1,1,festive,0,0.802982,0,paid,1.168117,0.977266,0,0,0.459660,3.13,177,98,40.0,31.0,37.0,35.428571,35.428571,3.994043,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008
14639,2024-12-31,SKU0040,37,1418.00,52466.00,1,0.2331,12,1,1,0,1,1,festive,0,1.027837,0,organic,1.165809,1.000552,0,0,0.572224,3.13,177,26,27.0,38.0,44.0,34.857143,34.857143,4.913538,438,173,341,5,64,SUP008,OrbitLine Sourcing,5,4,438,173,341,5,64,SUP008

In [136]:
master_df = master_df.sort_values(['sku_id' , 'date'])

In [137]:
master_df.to_csv('master_inventory_data.csv', index = False)